Make travis install nodejs v7
I get a installation error when setting up apm.

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found
(required by /home/travis/atom/usr/share/atom/resources/app/apm/
node_modules/git-utils/build/Release/git.node)

Maybe we need a more recent version of node, the default is 0.10